export enum ActionType {
  SET_DATA = 'SET_DATA',
  SET_ERROR = 'SET_ERROR',

  SET_SEARCH_TITLE = 'SET_SEARCH_TITLE',
  SET_SEARCH_GENRE_IDS = 'SET_SEARCH_GENRE_IDS',
  SET_SEARCH_YEAR = 'SET_SEARCH_YEAR',
}
